# Generated by Django 5.0.2 on 2024-03-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('laplacian_variance', models.FloatField()),
                ('noise', models.FloatField()),
                ('contrast', models.FloatField()),
                ('saturation', models.FloatField()),
                ('ssim_score', models.FloatField()),
                ('brightness', models.FloatField()),
                ('blur', models.BooleanField()),
                ('focus', models.BooleanField()),
                ('is_clear', models.BooleanField()),
            ],
        ),
    ]
